CXX=icpc

CXXFLAGS=-I/opt/boost/include/boost-1_41
LDFLAGS=-L/opt/boost/lib -lboost_system-il-mt -lboost_program_options-il-mt
timeline	:	timeline.cpp
	$(CXX) $(CXXFLAGS) timeline.cpp -o $@  $(LDFLAGS)

# DO NOT DELETE
