# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

gcc:
  image: gcc
  script: |
    wget -q https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
    apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
    rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
    echo "deb https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
    apt-get update
    apt-get install -y \
    intel-oneapi-mkl-devel \
    cmake \
    python3-pytest python3-pandas python3-numpy
    source /opt/intel/oneapi/setvars.sh
    export PATH=${PATH}:${PWD}/VEF/bin
    AR=xiar ./build.sh -c gfortran -b debug
    AR=xiar ./build.sh -c gfortran -b release -t
    cd test
    pytest --update=logout -v -k fcc12 -k bcc24

gcc48:
    image: gcc
    script: |
        wget -q https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
        apt-get update
        apt-get install -y \
        intel-oneapi-mkl-devel \
        cmake \
        python3-pytest python3-pandas python3-numpy
        source /opt/intel/oneapi/setvars.sh
        export PATH=${PATH}:${PWD}/VEF/bin
        AR=xiar ./build.sh -c gfortran -b debug
        AR=xiar ./build.sh -c gfortran -b release -t
        cd test
        pytest --update=logout -v -k bcc48

ifort:
  image: intel/oneapi-hpckit:devel-ubuntu22.04
  script: |
    apt-get update
    apt-get install -y \
    python3-pip
    pip install pandas pytest numpy
    export PATH=${PATH}:${PWD}/VEF/bin
    AR=xiar ./build.sh -c ifort -b debug
    AR=xiar ./build.sh -c ifort -b release -t
    cd test
    pytest --update=logout -v -k fcc12 -k bcc24

ifort48: 
  image: intel/oneapi-hpckit:devel-ubuntu22.04
  script: |
    apt-get update
    apt-get install -y \
    python3-pip
    pip install pandas pytest numpy
    export PATH=${PATH}:${PWD}/VEF/bin
    AR=xiar ./build.sh -c ifort -b debug
    AR=xiar ./build.sh -c ifort -b release -t
    cd test
    pytest --update=logout -v -k bcc48

ifx:
  image: intel/oneapi-hpckit:devel-ubuntu22.04
  script: |
    apt-get update
    apt-get install -y \
    python3-pip
    pip install pandas pytest numpy
    export PATH=${PATH}:${PWD}/VEF/bin
    AR=xiar ./build.sh -c ifx -b debug
    AR=xiar ./build.sh -c ifx -b release -t
    cd test
    pytest --update=logout -v -k fcc12 -k bcc24

ifx48: 
  image: intel/oneapi-hpckit:devel-ubuntu22.04
  script: |
    apt-get update
    apt-get install -y \
    python3-pip
    pip install pandas pytest numpy
    export PATH=${PATH}:${PWD}/VEF/bin
    AR=xiar ./build.sh -c ifx -b debug
    AR=xiar ./build.sh -c ifx -b release -t
    cd test
    pytest --update=logout -v -k bcc48

