# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

gcc:
  image: gcc
  script: |
    echo "deb [allow-insecure=yes] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
    apt-get update
    apt-get install --allow-unauthenticated -y \
    intel-oneapi-mkl-devel \
    cmake \
    python3-pytest python3-pandas python3-numpy
    source /opt/intel/oneapi/setvars.sh
    export PATH=${PATH}:${PWD}/VEF/bin
    AR=xiar ./build.sh -c gfortran -b debug
    AR=xiar ./build.sh -c gfortran -b release
    cd test
    export OMP_NUM_THREADS=3
    pytest --update=logout -v
ifx:
  image: intel/oneapi-hpckit:latest
  script: |
    apt-get update --allow-insecure-repositories
    apt-get install --allow-unauthenticated -y \
    cmake \
    python3-pip
    pip install pandas pytest numpy
    export PATH=${PATH}:${PWD}/VEF/bin
    AR=xiar ./build.sh -c ifx -b debug
    AR=xiar ./build.sh -c ifx -b release
    cd test
    export OMP_NUM_THREADS=3
    pytest --update=logout -v
