# $Id: Makefile 3345 2020-01-23 21:31:07Z Hadi.Ghiabakloo $
#
#
#HGH:
CMAKE_FLAGS='-DCMAKE_CXX_COMPILER=/apps/leuven/ivybridge/2018a/software/icc/2018.1.163-GCC-6.4.0-2.28/compilers_and_libraries_2018.1.163/linux/bin/intel64/icpc'

CMAKELISTS=CMakeLists.txt

include ../build/cmake-common/bootstrap.makefile

