#
# $Id$
#

# 
# Configuration on VIC3
# 
ifeq ($(BUILDHOST),vic3)
     # MKLROOT is set via environment variable
     MKLPATH=$(MKLROOT)/lib/$(MKL_TARGET_ARCH)
     MKLINCLUDE= -I$(MKLROOT)/include/$(MKL_TARGET_ARCH)/lp64
     ifeq ($(INTEL_COMPILER_VERSION),13.0)
     MKLLDFLAGS +=  -Wl,--start-group  $(MKLROOT)/lib/intel64/libmkl_intel_lp64.a $(MKLROOT)/lib/intel64/libmkl_sequential.a $(MKLROOT)/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm
     else
     MKLLDFLAGS += $(MKLPATH)/libmkl_solver_lp64_sequential.a -Wl,--start-group $(MKLPATH)/libmkl_intel_lp64.a $(MKLPATH)/libmkl_sequential.a $(MKLPATH)/libmkl_core.a -Wl,--end-group -lpthread
     endif
endif

#
# Configuration on dijkstra
# 
ifeq ($(BUILDHOST),dijkstra)
     # MKLROOT is set via environment variable
     MKLINCLUDE= -I$(MKLROOT)/include/$(MKL_TARGET_ARCH)/lp64
     MKLPATH=$(MKLROOT)/lib/$(MKL_TARGET_ARCH)
     MKLLDFLAGS += $(MKLPATH)/libmkl_solver_lp64_sequential.a -Wl,--start-group $(MKLPATH)/libmkl_intel_lp64.a $(MKLPATH)/libmkl_sequential.a $(MKLPATH)/libmkl_core.a -Wl,--end-group -lpthread
endif
#
