#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from configGeneric import configGeneric

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1464273519.157
__CHEETAH_genTimestamp__ = 'Thu May 26 16:38:39 2016'
__CHEETAH_src__ = 'configUDSA.tmpl'
__CHEETAH_srcLastModified__ = 'Thu May 26 16:04:06 2016'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class configUDSA(configGeneric):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(configUDSA, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def moduleConfig(self, **KWS):



        ## CHEETAH: generated from #block moduleConfig at line 2, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Module UDSA section
# ==================
''')
        _orig_filter_18022086 = _filter
        filterName = u'FilterChain'
        if self._CHEETAH__filters.has_key("FilterChain"):
            _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
        else:
            _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
        _v = VFFSL(SL,"udsa.sample_orientation.orientation",True) # u'$udsa.sample_orientation.orientation' on line 7, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$udsa.sample_orientation.orientation')) # from line 7, col 1.
        write(u''' # Sample orientation type
''')
        if VFFSL(SL,"udsa.sample_orientation.orientation",True) == 'inplane': # generated from line 8, col 1
            _v = VFFSL(SL,"range",False)(VFFSL(SL,"udsa.sample_orientation.range",True), 'alpha angles') # u"$range($udsa.sample_orientation.range, 'alpha angles')" on line 9, col 1
            if _v is not None: write(_filter(_v, rawExpr=u"$range($udsa.sample_orientation.range, 'alpha angles')")) # from line 9, col 1.
        elif VFFSL(SL,"udsa.sample_orientation.orientation",True) == 'arbitrary': # generated from line 10, col 1
            _v = VFFSL(SL,"udsa.sample_orientation.euler_angles",True) # u'${udsa.sample_orientation.euler_angles, plain=True}' on line 11, col 1
            if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${udsa.sample_orientation.euler_angles, plain=True}')) # from line 11, col 1.
            write(u''' # Euler angles that define the chosen loading direction
''')
        _v = VFFSL(SL,"udsa.scaling.type",True) # u'$udsa.scaling.type' on line 13, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$udsa.scaling.type')) # from line 13, col 1.
        write(u''' # Keyword: incrementation type
''')
        _v = VFFSL(SL,"udsa.scaling.total_magnitude",True) # u'$udsa.scaling.total_magnitude' on line 14, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$udsa.scaling.total_magnitude')) # from line 14, col 1.
        write(u''' # Maximal deformation
''')
        _v = VFFSL(SL,"udsa.scaling.increment_magnitude",True) # u'$udsa.scaling.increment_magnitude' on line 15, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$udsa.scaling.increment_magnitude')) # from line 15, col 1.
        write(u''' # Increment deformation
''')
        _v = VFFSL(SL,"udsa.stress_state",True) # u'$udsa.stress_state' on line 16, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$udsa.stress_state')) # from line 16, col 1.
        write(u""" # Stress state: 'compression' or 'tension'
""")
        _v = VFFSL(SL,"udsa.use_default_settings",True) # u'$udsa.use_default_settings' on line 17, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$udsa.use_default_settings')) # from line 17, col 1.
        write(u''' # Flag: use default settings 
''')
        if not VFFSL(SL,"udsa.use_default_settings",True): # generated from line 18, col 1
            _v = VFFSL(SL,"udsa.stress_ratio",True) # u'$udsa.stress_ratio' on line 19, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$udsa.stress_ratio')) # from line 19, col 1.
            write(u''' # Stress ratio: rho = sigma_yy/sigma_xx
''')
        _filter = self._CHEETAH__currentFilter = _orig_filter_18022086
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        self.moduleConfig(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_configUDSA= 'writeBody'

## END CLASS DEFINITION

if not hasattr(configUDSA, '_initCheetahAttributes'):
    templateAPIClass = getattr(configUDSA, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(configUDSA)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=configUDSA()).run()


