#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from configGeneric import configGeneric

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1458654524.707
__CHEETAH_genTimestamp__ = 'Tue Mar 22 14:48:44 2016'
__CHEETAH_src__ = 'configYLD.tmpl'
__CHEETAH_srcLastModified__ = 'Mon Mar 21 14:41:00 2016'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class configYLD(configGeneric):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(configYLD, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def moduleConfig(self, **KWS):



        ## CHEETAH: generated from #block moduleConfig at line 2, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Module YLD section
# ==================
''')
        _orig_filter_17820928 = _filter
        filterName = u'FilterChain'
        if self._CHEETAH__filters.has_key("FilterChain"):
            _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
        else:
            _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
        _v = VFFSL(SL,"range",False)(VFFSL(SL,"yld.range",True)) # u'$range($yld.range)' on line 7, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$range($yld.range)')) # from line 7, col 1.
        _v = VFFSL(SL,"yld.use_default_settings",True) # u'$yld.use_default_settings' on line 8, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$yld.use_default_settings')) # from line 8, col 1.
        write(u''' # Flag: use default yield section settings
''')
        if not VFFSL(SL,"yld.use_default_settings",True): # generated from line 9, col 1
            _v = VFFSL(SL,"yld.normalize_base",True) # u'$yld.normalize_base' on line 10, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$yld.normalize_base')) # from line 10, col 1.
            write(u''' # normalize base tensors
''')
            _v = VFFSL(SL,"yld.base_sigma_x",True) # u'$yld.base_sigma_x' on line 11, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$yld.base_sigma_x')) # from line 11, col 1.
            write(u''' # first base vector
''')
            _v = VFFSL(SL,"yld.base_sigma_y",True) # u'$yld.base_sigma_y' on line 12, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$yld.base_sigma_y')) # from line 12, col 1.
            write(u''' # second base vector
''')
            _v = VFFSL(SL,"yld.base_sigma_y",True) # u'$yld.base_sigma_y' on line 13, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$yld.base_sigma_y')) # from line 13, col 1.
            write(u''' # offset vector
''')
            _v = VFFSL(SL,"yld.normalize_stress",True) # u'$yld.normalize_stress' on line 14, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$yld.normalize_stress')) # from line 14, col 1.
            write(u''' # Flag: normalize stress
''')
            _v = VFFSL(SL,"range",False)(VFFSL(SL,"yld.w_range",True)) # u'$range($yld.w_range)' on line 15, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$range($yld.w_range)')) # from line 15, col 1.
            _v = VFFSL(SL,"yld.scale_section",True) # u'$yld.scale_section' on line 16, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$yld.scale_section')) # from line 16, col 1.
            write(u'''
''')
            if VFFSL(SL,"yld.scale_section",True): # generated from line 17, col 1
                _v = VFFSL(SL,"yld.scaling_sigma",True) # u'$yld.scaling_sigma' on line 18, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'$yld.scaling_sigma')) # from line 18, col 1.
                write(u''' # Stress direction used for scaling the yield section
''')
        _filter = self._CHEETAH__currentFilter = _orig_filter_17820928
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        self.moduleConfig(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_configYLD= 'writeBody'

## END CLASS DEFINITION

if not hasattr(configYLD, '_initCheetahAttributes'):
    templateAPIClass = getattr(configYLD, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(configYLD)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=configYLD()).run()


