#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from config import config

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1466063454.961
__CHEETAH_genTimestamp__ = 'Thu Jun 16 09:50:54 2016'
__CHEETAH_src__ = 'configGeneric.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Mar 30 18:02:22 2016'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class configGeneric(config):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(configGeneric, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def commonConfig(self, **KWS):



        ## CHEETAH: generated from #block commonConfig at line 2, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Generic section
# ===============
''')
        _orig_filter_42059680 = _filter
        filterName = u'FilterChain'
        if self._CHEETAH__filters.has_key("FilterChain"):
            _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
        else:
            _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
        _v = VFFSL(SL,"output_prefix",True) # u'$output_prefix' on line 7, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$output_prefix')) # from line 7, col 1.
        write(u''' # Prefix for the output files
''')
        _v = VFFSL(SL,"output_request",True) # u'$output_request' on line 8, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$output_request')) # from line 8, col 1.
        write(u''' # Flag: request incremental output of the material state
''')
        _v = VFFSL(SL,"verbosity",True) # u'$verbosity' on line 9, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$verbosity')) # from line 9, col 1.
        write(u''' # Verbosity level: 0 (the lowest) - 3 (the highest)
''')
        _v = VFFSL(SL,"input_fname",True) # u'$input_fname' on line 10, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$input_fname')) # from line 10, col 1.
        write(u''' # Path to the texture file
''')
        _v = VFFSL(SL,"model_type",True) # u'$model_type' on line 11, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$model_type')) # from line 11, col 1.
        write(u''' # Model type: either ALAMEL or FCTaylor
''')
        _v = VFFSL(SL,"slipsystems",True) # u'$slipsystems' on line 12, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$slipsystems')) # from line 12, col 1.
        write(u''' # Family of slip systems
''')
        _v = VFFSL(SL,"use_default_microstructure",True) # u'$use_default_microstructure' on line 13, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$use_default_microstructure')) # from line 13, col 1.
        write(u''' # Flag: use default microstructural description
''')
        if not VFFSL(SL,"use_default_microstructure",True): # generated from line 14, col 1
            _v = VFFSL(SL,"microstructure.microstructure_fname",True) # u'$microstructure.microstructure_fname' on line 15, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$microstructure.microstructure_fname')) # from line 15, col 1.
            write(u''' # Microstructure definition (filename)
''')
            _orig_filter_82538875 = _filter
            filterName = u'TensorFilter'
            if self._CHEETAH__filters.has_key("TensorFilter"):
                _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
            else:
                _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
            _v = VFFSL(SL,"microstructure.Fmicro",True) # u'$microstructure.Fmicro' on line 17, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$microstructure.Fmicro')) # from line 17, col 1.
            write(u'''          # Deformation gradient
''')
            _filter = self._CHEETAH__currentFilter = _orig_filter_82538875
        _v = VFFSL(SL,"use_default_hardening",True) # u'$use_default_hardening' on line 20, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$use_default_hardening')) # from line 20, col 1.
        write(u''' # Flag: use default hardening
''')
        if not VFFSL(SL,"use_default_hardening",True): # generated from line 21, col 1
            _v = VFFSL(SL,"hardening.hardening_type",True) # u'$hardening.hardening_type' on line 22, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$hardening.hardening_type')) # from line 22, col 1.
            write(u''' # Hardening law Id
''')
            if VFFSL(SL,"hardening.hardening_type",True) == 2: # generated from line 23, col 1
                _v = VFFSL(SL,"hardening.SwiftK.K",True) # u'${hardening.SwiftK.K,width=6}' on line 24, col 1
                if _v is not None: write(_filter(_v,width=6, rawExpr=u'${hardening.SwiftK.K,width=6}')) # from line 24, col 1.
                write(u''' ''')
                _v = VFFSL(SL,"hardening.SwiftK.gamma0",True) # u'${hardening.SwiftK.gamma0,width=6}' on line 24, col 31
                if _v is not None: write(_filter(_v,width=6, rawExpr=u'${hardening.SwiftK.gamma0,width=6}')) # from line 24, col 31.
                write(u''' ''')
                _v = VFFSL(SL,"hardening.SwiftK.n",True) # u'${hardening.SwiftK.n,width=6}' on line 24, col 66
                if _v is not None: write(_filter(_v,width=6, rawExpr=u'${hardening.SwiftK.n,width=6}')) # from line 24, col 66.
                write(u''' # Coefficients of SwiftK hardening law
''')
            elif VFFSL(SL,"hardening.hardening_type",True) == 3: # generated from line 25, col 1
                _v = VFFSL(SL,"hardening.SwiftS.crss0",True) # u'${hardening.SwiftS.crss0,width=6}' on line 26, col 1
                if _v is not None: write(_filter(_v,width=6, rawExpr=u'${hardening.SwiftS.crss0,width=6}')) # from line 26, col 1.
                write(u''' ''')
                _v = VFFSL(SL,"hardening.SwiftS.gamma0",True) # u'${hardening.SwiftS.gamma0,width=6}' on line 26, col 35
                if _v is not None: write(_filter(_v,width=6, rawExpr=u'${hardening.SwiftS.gamma0,width=6}')) # from line 26, col 35.
                write(u''' ''')
                _v = VFFSL(SL,"hardening.SwiftS.n",True) # u'${hardening.SwiftS.n,width=6}' on line 26, col 70
                if _v is not None: write(_filter(_v,width=6, rawExpr=u'${hardening.SwiftS.n,width=6}')) # from line 26, col 70.
                write(u''' # Coefficients of SwiftS hardening law
''')
        _v = VFFSL(SL,"use_default_solver_settings",True) # u'$use_default_solver_settings' on line 29, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$use_default_solver_settings')) # from line 29, col 1.
        write(u''' # Flag: use default solver settings
''')
        if not VFFSL(SL,"use_default_solver_settings",True): # generated from line 30, col 1
            _v = VFFSL(SL,"solver.jacobi_eps",True) # u'$solver.jacobi_eps' on line 31, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$solver.jacobi_eps')) # from line 31, col 1.
            write(u''' # Control over numerical estimation of Jacobian
''')
            _v = VFFSL(SL,"solver.attempt_linearize",True) # u'$solver.attempt_linearize' on line 32, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$solver.attempt_linearize')) # from line 32, col 1.
            write(u''' # Flag: attempt to linearize the problem
''')
            _v = VFFSL(SL,"solver.default_eps",True) # u'${solver.default_eps, width=10}' on line 33, col 1
            if _v is not None: write(_filter(_v, width=10, rawExpr=u'${solver.default_eps, width=10}')) # from line 33, col 1.
            write(u''' ''')
            _v = VFFSL(SL,"solver.objective_eps",True) # u'${solver.objective_eps, width=9}' on line 33, col 33
            if _v is not None: write(_filter(_v, width=9, rawExpr=u'${solver.objective_eps, width=9}')) # from line 33, col 33.
            write(u''' # Default eps for TR-solver, eps for the norm of objective function: ||F||_2
''')
            _v = VFFSL(SL,"solver.use_advanced_settings",True) # u'$solver.use_advanced_settings' on line 34, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$solver.use_advanced_settings')) # from line 34, col 1.
            write(u''' # Flag: use advanced solver settings
''')
        _filter = self._CHEETAH__currentFilter = _orig_filter_42059680
        write(u'''# End of generic section
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        self.commonConfig(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_configGeneric= 'writeBody'

## END CLASS DEFINITION

if not hasattr(configGeneric, '_initCheetahAttributes'):
    templateAPIClass = getattr(configGeneric, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(configGeneric)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=configGeneric()).run()


