#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from configGeneric import configGeneric

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1458654524.513
__CHEETAH_genTimestamp__ = 'Tue Mar 22 14:48:44 2016'
__CHEETAH_src__ = 'configASR.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Mar 22 12:33:57 2016'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class configASR(configGeneric):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(configASR, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def moduleConfig(self, **KWS):



        ## CHEETAH: generated from #block moduleConfig at line 2, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Module ASR section
# ==================
''')
        _orig_filter_97932372 = _filter
        filterName = u'FilterChain'
        if self._CHEETAH__filters.has_key("FilterChain"):
            _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
        else:
            _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
        _v = VFFSL(SL,"asr.reference_frame",True) # u'${asr.reference_frame, plain=True}' on line 7, col 1
        if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${asr.reference_frame, plain=True}')) # from line 7, col 1.
        write(u''' # Euler angles defining sample reference frame
''')
        _v = VFFSL(SL,"len",False)(VFFSL(SL,"asr.steps",True)) # u'$len($asr.steps)' on line 8, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$len($asr.steps)')) # from line 8, col 1.
        write(u''' # Number of steps
''')
        for istep,step in VFFSL(SL,"enumerate",False)(VFFSL(SL,"asr.steps",True)): # generated from line 9, col 1
            write(u'''# Step ''')
            _v = VFFSL(SL,"istep",True) # u'$istep' on line 10, col 8
            if _v is not None: write(_filter(_v, rawExpr=u'$istep')) # from line 10, col 8.
            write(u'''
''')
            _v = VFFSL(SL,"step.stress_mode",True) # u'${step.stress_mode, plain=True}' on line 11, col 1
            if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${step.stress_mode, plain=True}')) # from line 11, col 1.
            write(u''' # Stress mode
''')
            _v = VFFSL(SL,"step.update_state",True) # u'$step.update_state' on line 12, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$step.update_state')) # from line 12, col 1.
            write(u''' # Flag: incrementally update state variables
''')
            if VFFSL(SL,"step.update_state",True): # generated from line 13, col 1
                _v = VFFSL(SL,"step.scaling.type",True) # u'$step.scaling.type' on line 14, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'$step.scaling.type')) # from line 14, col 1.
                write(u''' # Keyword: incrementation type
''')
                _v = VFFSL(SL,"step.scaling.total_magnitude",True) # u'$step.scaling.total_magnitude' on line 15, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'$step.scaling.total_magnitude')) # from line 15, col 1.
                write(u''' # Magnitude of the step
''')
                _v = VFFSL(SL,"step.scaling.increment_magnitude",True) # u'$step.scaling.increment_magnitude' on line 16, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'$step.scaling.increment_magnitude')) # from line 16, col 1.
                write(u''' # Magnitude of the increment
''')
        _filter = self._CHEETAH__currentFilter = _orig_filter_97932372
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        self.moduleConfig(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_configASR= 'writeBody'

## END CLASS DEFINITION

if not hasattr(configASR, '_initCheetahAttributes'):
    templateAPIClass = getattr(configASR, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(configASR)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=configASR()).run()


