#!/bin/bash

CRYS2D=crys3D
COMMFILE=outcomm.dat

TIMEOUT=360

rm -f PPD RST CHECK* ACTIV DACTIV POLE* EULER  "${COMMFILE}"

ln -s ../RST RST

if [ -n $(which timedrun 2> /dev/null) ] ; then
	timedrun -t "${TIMEOUT}" "${CRYS2D}"
else
	"${CRYS2D}"
fi

