#!/bin/bash
# Use defaults
import defaults.sh

## Global configuration section

# Set location of scratch directory
if [ -n "$PBS_O_WORKDIR" ] ; then
        SCRATCH="${VSC_SCRATCH_NODE}/recalcYL.XXXXXXXX"
else
        SCRATCH="/tmp/recalcYL.XXXXXXXX"
fi

# Number of processors for multilevel facet calculations (default 2)
NPROC=4

