#
# $Id$
#
#### Selection of toolset
## Note that only one toolset can be used 
######################################################################
#### Toolset:
# Intel toolset
#
# Intel Fortran compiler
FC=ifort
#
# Intel library manager 
AR=xiar
#
# Documentation generator
DOXYGEN=doxygen
#
######################################################################
# Use per-host configuration plugin
# 
ifndef ROOTDIR
ROOTDIR=../..
endif

include $(ROOTDIR)/build-tools/Makefile.host
$(info Configuration for $(BUILDHOST))
#
######################################################################

FCFLAGS=-fpp -module $(INCLUDEDIR) 

ifdef DEBUG
ConfigurationName=debug
LIBDIR=debug
DEBUGFLAGS= -O0 -g -debug full -check all
FCFLAGS+= $(DEBUGFLAGS)
TRANSCONFIG=DEBUG=1
else
ConfigurationName=release
LIBDIR=release
OPTFLAGS=-O3 -fast
FCFLAGS+= $(OPTFLAGS)
endif
#
######################################################################
OBJDIR=$(ConfigurationName)/obj
INCLUDEDIR=$(ConfigurationName)/include

## Dependencies:
LIBALAMELDIR=../../$(ROOTDIR)/MTM/branches/alamelSub/src/$(ConfigurationName)/lib
FCFLAGS+= -I$(LIBALAMELDIR)/include
FLDFLAGS+= $(LIBALAMELDIR)/libalamel.a

LIBOPTROOT=$(TOOLSDIR)/fng/utils/optlib
LIBOPTDIR=$(LIBOPTROOT)/$(ConfigurationName)
FCFLAGS+= -I$(LIBOPTDIR)/include

# Name of the library
LIBOPTNAME=libopt.a
LIBOPTPATH=$(LIBOPTDIR)/$(LIBOPTNAME)
FLDFLAGS+= $(LIBOPTPATH)
# MKL subroutines
#
# Configuration on dijkstra
# 
ifeq ($(BUILDHOST),dijkstra)
MKLINCLUDE= -I$(MKLROOT)/include/$(MKL_TARGET_ARCH)/lp64
MKLPATH=$(MKLROOT)/lib/$(MKL_TARGET_ARCH)
MKLLDFLAGS += $(MKLPATH)/libmkl_solver_lp64_sequential.a -Wl,--start-group $(MKLPATH)/libmkl_intel_lp64.a $(MKLPATH)/libmkl_sequential.a $(MKLPATH)/libmkl_core.a -Wl,--end-group -lpthread
LIBFCFLAGS += $(MKLINCLUDE) # -check bounds
endif
ifeq ($(BUILDHOST),vic3)
MKLINCLUDE= -I$(MKLROOT)/include/$(MKL_TARGET_ARCH)/lp64
MKLPATH=$(MKLROOT)/lib/$(MKL_TARGET_ARCH)
MKLLDFLAGS += $(MKLPATH)/libmkl_solver_lp64_sequential.a -Wl,--start-group $(MKLPATH)/libmkl_intel_lp64.a $(MKLPATH)/libmkl_sequential.a $(MKLPATH)/libmkl_core.a -Wl,--end-group -lpthread
LIBFCFLAGS += $(MKLINCLUDE) # -check bounds
endif
#

