#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from configGeneric import configGeneric

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1466063454.939
__CHEETAH_genTimestamp__ = 'Thu Jun 16 09:50:54 2016'
__CHEETAH_src__ = 'configEWC.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Jun 16 09:45:41 2016'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class configEWC(configGeneric):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(configEWC, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def moduleConfig(self, **KWS):



        ## CHEETAH: generated from #block moduleConfig at line 2, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Module EWC section
# ==================
''')
        _orig_filter_57527238 = _filter
        filterName = u'FilterChain'
        if self._CHEETAH__filters.has_key("FilterChain"):
            _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
        else:
            _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
        _v = VFFSL(SL,"ewc.worklevel_selection_method",True) # u'$ewc.worklevel_selection_method' on line 7, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ewc.worklevel_selection_method')) # from line 7, col 1.
        write(u''' # Keyword: method for selecting worklevel
''')
        if VFFSL(SL,"ewc.worklevel_selection_method",True) == 'reference': # generated from line 8, col 1
            _v = VFFSL(SL,"ewc.reference.stress_mode",True) # u'${ewc.reference.stress_mode, plain=True}' on line 9, col 1
            if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${ewc.reference.stress_mode, plain=True}')) # from line 9, col 1.
            write(u''' # Reference stress mode
''')
            _v = VFFSL(SL,"ewc.reference.scaling.type",True) # u'$ewc.reference.scaling.type' on line 10, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$ewc.reference.scaling.type')) # from line 10, col 1.
            write(u''' # Keyword: incrementation type
''')
            _v = VFFSL(SL,"ewc.reference.scaling.step_magnitude",True) # u'$ewc.reference.scaling.step_magnitude' on line 11, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$ewc.reference.scaling.step_magnitude')) # from line 11, col 1.
            write(u''' # Magnitude of the step
''')
            _v = VFFSL(SL,"ewc.reference.scaling.increment_magnitude",True) # u'$ewc.reference.scaling.increment_magnitude' on line 12, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$ewc.reference.scaling.increment_magnitude')) # from line 12, col 1.
            write(u''' # Magnitude of the increment
''')
        _v = VFFSL(SL,"range",False)(VFFSL(SL,"ewc.contour_theta_range",True), 'theta angles at which the contours will be computed') # u"$range($ewc.contour_theta_range, 'theta angles at which the contours will be computed')" on line 14, col 1
        if _v is not None: write(_filter(_v, rawExpr=u"$range($ewc.contour_theta_range, 'theta angles at which the contours will be computed')")) # from line 14, col 1.
        _v = VFFSL(SL,"range",False)(VFFSL(SL,"ewc.contour_levels_range",True), 'contour levels') # u"$range($ewc.contour_levels_range, 'contour levels')" on line 15, col 1
        if _v is not None: write(_filter(_v, rawExpr=u"$range($ewc.contour_levels_range, 'contour levels')")) # from line 15, col 1.
        _v = VFFSL(SL,"ewc.points_per_contour",True) # u'$ewc.points_per_contour' on line 16, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ewc.points_per_contour')) # from line 16, col 1.
        write(u''' # Number of data points per contour level along each evolution line
''')
        _v = VFFSL(SL,"ewc.use_default_settings",True) # u'$ewc.use_default_settings' on line 17, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$ewc.use_default_settings')) # from line 17, col 1.
        write(u''' # Flag: use default settings
''')
        if not VFFSL(SL,"ewc.use_default_settings",True): # generated from line 18, col 1
            _v = VFFSL(SL,"ewc.base_sigma_x",True) # u'${ewc.base_sigma_x, plain=True}' on line 19, col 1
            if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${ewc.base_sigma_x, plain=True}')) # from line 19, col 1.
            write(u''' # first base tensor in Voigt notation
''')
            _v = VFFSL(SL,"ewc.base_sigma_y",True) # u'${ewc.base_sigma_y, plain=True}' on line 20, col 1
            if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${ewc.base_sigma_y, plain=True}')) # from line 20, col 1.
            write(u''' # second base tensor in Voigt notation
''')
        _filter = self._CHEETAH__currentFilter = _orig_filter_57527238
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        self.moduleConfig(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_configEWC= 'writeBody'

## END CLASS DEFINITION

if not hasattr(configEWC, '_initCheetahAttributes'):
    templateAPIClass = getattr(configEWC, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(configEWC)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=configEWC()).run()


