# 
# $Id$
#
# Definitions of various useful constructs and functions
#

#
# Canned receips, implicit targets and functions
#

# Build-up of the directory structure
define create-dir
@echo $@
[ -d $@ ] || mkdir -p $@
endef


# fxx2o uilds a list of object names from a list of .for or .f90 files.
# Arg #1: list of source files 
fxx2o = $(subst .for,.o, $(filter %.for,$(1))) $(subst .f90,.o, $(filter %.f90,$(1)))

# fxx2opaths builds (relative) object paths from a list of .for or .90 files.
# Arg #1: list of source files
# Arg #2: path to the directory where the object files shall be stored.
fxx2opaths = $(patsubst %, $(2)/%,$(call fxx2o,$(1)))


