#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from configGeneric import configGeneric

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1487078179.306
__CHEETAH_genTimestamp__ = 'Tue Feb 14 14:16:19 2017'
__CHEETAH_src__ = 'configADP.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Feb 14 12:21:59 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class configADP(configGeneric):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(configADP, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def moduleConfig(self, **KWS):



        ## CHEETAH: generated from #block moduleConfig at line 2, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Module ADP section
# ==================
''')
        _orig_filter_23416173 = _filter
        filterName = u'FilterChain'
        if self._CHEETAH__filters.has_key("FilterChain"):
            _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
        else:
            _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
        _v = VFFSL(SL,"len",False)(VFFSL(SL,"adp.steps",True)) # u'$len($adp.steps)' on line 7, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$len($adp.steps)')) # from line 7, col 1.
        write(u''' # Number of steps
''')
        for istep,step in VFFSL(SL,"enumerate",False)(VFFSL(SL,"adp.steps",True), 1): # generated from line 8, col 1
            write(u'''# Step ''')
            _v = VFFSL(SL,"istep",True) # u'$istep' on line 9, col 8
            if _v is not None: write(_filter(_v, rawExpr=u'$istep')) # from line 9, col 8.
            write(u'''
''')
            step_type = None
            step_types = ['Deformation', 'StrainMode', 'Strain', None]
            for step_type in VFFSL(SL,"step_types",True): # generated from line 12, col 1
                if step_type in VFN(VFFSL(SL,"step",True),"keys",False)(): # generated from line 13, col 1
                    break
            _v = VFFSL(SL,"step_type",True) # u'$step_type' on line 17, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$step_type')) # from line 17, col 1.
            write(u''' # Keyword: deformation type  
''')
            if VFFSL(SL,"step_type",True) == 'Deformation': # generated from line 18, col 1
                _v = VFFSL(SL,"step.Deformation",True) # u'${step.Deformation, plain=True}' on line 19, col 1
                if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${step.Deformation, plain=True}')) # from line 19, col 1.
                write(u''' # Full deformation rate tensor in Voigt notation: 9 components
''')
            elif VFFSL(SL,"step_type",True) == 'StrainMode': # generated from line 20, col 1
                _v = VFFSL(SL,"step.StrainMode",True) # u'${step.StrainMode, plain=True}' on line 21, col 1
                if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${step.StrainMode, plain=True}')) # from line 21, col 1.
                write(u''' # Strain mode in Voigt notation: 6 components
''')
                _v = VFFSL(SL,"step.magnitude",True) # u'${step.magnitude}' on line 22, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'${step.magnitude}')) # from line 22, col 1.
                write(u''' # Magnitude of the step
''')
            elif VFFSL(SL,"step_type",True) == 'Strain': # generated from line 23, col 1
                _v = VFFSL(SL,"step.Strain",True) # u'${step.Strain, plain=True}' on line 24, col 1
                if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${step.Strain, plain=True}')) # from line 24, col 1.
                write(u''' # Strain increment in Voigt notation: 6 components
''')
            _v = VFFSL(SL,"step.update_state",True) # u'$step.update_state' on line 26, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$step.update_state')) # from line 26, col 1.
            write(u''' # Flag: incrementally update state variables
''')
            _v = VFFSL(SL,"step.incrementation",True) # u'$step.incrementation' on line 27, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$step.incrementation')) # from line 27, col 1.
            write(u''' # Keyword: incrementation type
''')
        _filter = self._CHEETAH__currentFilter = _orig_filter_23416173
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        self.moduleConfig(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_configADP= 'writeBody'

## END CLASS DEFINITION

if not hasattr(configADP, '_initCheetahAttributes'):
    templateAPIClass = getattr(configADP, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(configADP)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=configADP()).run()


