# $Id$
#
#

# Set list of CMakeList files in project directories
CMAKELISTS=CMakeLists.txt  alamDMC/CMakeLists.txt  libAlamDMC/CMakeLists.txt  libAlamYLP/CMakeLists.txt

include ../build/cmake-common/bootstrap.makefile

