#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1487078179.29
__CHEETAH_genTimestamp__ = 'Tue Feb 14 14:16:19 2017'
__CHEETAH_src__ = 'config.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Feb 08 12:09:35 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class config(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(config, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def commonConfig(self, **KWS):



        ## CHEETAH: generated from #block commonConfig at line 4, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def moduleConfig(self, **KWS):



        ## CHEETAH: generated from #block moduleConfig at line 6, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def main(self, **KWS):



        ## CHEETAH: generated from #block main at line 2, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Note: this is an automatically generated config file.
''')
        self.commonConfig(trans=trans)
        self.moduleConfig(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def range(self, r, comment='', **KWS):



        ## CHEETAH: generated from #def range(r, comment='') at line 9, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        comment_ext = ': ' + VFFSL(SL,"comment",True) if VFFSL(SL,"comment",True) else ''
        #  There are ranges that not define r.params
        try : # generated from line 12, col 1
            rpar = VFFSL(SL,"r.params",True)
        except: # generated from line 14, col 1
            pass
        _v = VFFSL(SL,"r.type",True) # u'$r.type' on line 17, col 1
        if _v is not None: write(_filter(_v, rawExpr=u'$r.type')) # from line 17, col 1.
        write(u''' # Range type specification''')
        _v = VFFSL(SL,"comment_ext",True) # u'${comment_ext, bypass=True}' on line 17, col 35
        if _v is not None: write(_filter(_v, bypass=True, rawExpr=u'${comment_ext, bypass=True}')) # from line 17, col 35.
        write(u'''
''')
        if VFFSL(SL,"r.type",True) == 'uniform': # generated from line 18, col 1
            _v = VFFSL(SL,"rpar.begin",True) # u'${rpar.begin, width=6}' on line 19, col 1
            if _v is not None: write(_filter(_v, width=6, rawExpr=u'${rpar.begin, width=6}')) # from line 19, col 1.
            write(u''' ''')
            _v = VFFSL(SL,"rpar.end",True) # u'${rpar.end, width=6}' on line 19, col 24
            if _v is not None: write(_filter(_v, width=6, rawExpr=u'${rpar.end, width=6}')) # from line 19, col 24.
            write(u''' ''')
            _v = VFFSL(SL,"rpar.step",True) # u'${rpar.step, width=6}' on line 19, col 45
            if _v is not None: write(_filter(_v, width=6, rawExpr=u'${rpar.step, width=6}')) # from line 19, col 45.
            write(u""" # Range specification for 'uniform':  begin end step
""")
        elif VFFSL(SL,"r.type",True) in ['biased', 'doublebiased']: # generated from line 20, col 1
            _v = VFFSL(SL,"rpar.begin",True) # u'${rpar.begin, width=6}' on line 21, col 1
            if _v is not None: write(_filter(_v, width=6, rawExpr=u'${rpar.begin, width=6}')) # from line 21, col 1.
            write(u''' ''')
            _v = VFFSL(SL,"rpar.end",True) # u'${rpar.end, width=6}' on line 21, col 24
            if _v is not None: write(_filter(_v, width=6, rawExpr=u'${rpar.end, width=6}')) # from line 21, col 24.
            write(u''' ''')
            _v = VFFSL(SL,"rpar.bias",True) # u'${rpar.bias, width=6}' on line 21, col 45
            if _v is not None: write(_filter(_v, width=6, rawExpr=u'${rpar.bias, width=6}')) # from line 21, col 45.
            write(u''' # Range specification for ''')
            _v = VFFSL(SL,"r.type",True) # u'${r.type, bypass=True}' on line 21, col 93
            if _v is not None: write(_filter(_v, bypass=True, rawExpr=u'${r.type, bypass=True}')) # from line 21, col 93.
            write(u''':  begin end bias
''')
        elif VFFSL(SL,"r.type",True) == 'multibiased': # generated from line 22, col 1
            _v = VFFSL(SL,"rpar.begin",True) # u'$rpar.begin' on line 23, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$rpar.begin')) # from line 23, col 1.
            write(u''' # Begin of the range
''')
            _v = VFFSL(SL,"len",False)(VFFSL(SL,"rpar.subranges",True)) # u'$len($rpar.subranges)' on line 24, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$len($rpar.subranges)')) # from line 24, col 1.
            write(u''' # Number of subranges
''')
            for i,sr in VFFSL(SL,"enumerate",False)(VFFSL(SL,"rpar.subranges",True), 1): # generated from line 25, col 1
                _v = VFFSL(SL,"sr.end",True) # u'${sr.end, width=10}' on line 26, col 1
                if _v is not None: write(_filter(_v, width=10, rawExpr=u'${sr.end, width=10}')) # from line 26, col 1.
                write(u''' ''')
                _v = VFFSL(SL,"sr.bias",True) # u'${sr.bias, width=9}' on line 26, col 21
                if _v is not None: write(_filter(_v, width=9, rawExpr=u'${sr.bias, width=9}')) # from line 26, col 21.
                write(u''' # subrange ''')
                _v = VFFSL(SL,"i",True) # u'${i, bypass=True}' on line 26, col 52
                if _v is not None: write(_filter(_v, bypass=True, rawExpr=u'${i, bypass=True}')) # from line 26, col 52.
                write(u''': end, bias
''')
                _v = VFFSL(SL,"sr.npoints",True) # u'$sr.npoints' on line 27, col 1
                if _v is not None: write(_filter(_v, rawExpr=u'$sr.npoints')) # from line 27, col 1.
                write(u''' # subrange ''')
                _v = VFFSL(SL,"i",True) # u'${i, bypass=True}' on line 27, col 24
                if _v is not None: write(_filter(_v, bypass=True, rawExpr=u'${i, bypass=True}')) # from line 27, col 24.
                write(u''': number of points 
''')
        elif VFFSL(SL,"r.type",True) == 'discrete': # generated from line 29, col 1
            _v = VFFSL(SL,"len",False)(VFFSL(SL,"rpar.values",True)) # u'$len($rpar.values)' on line 30, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$len($rpar.values)')) # from line 30, col 1.
            write(u''' # number of points in the range
''')
            _v = VFFSL(SL,"rpar.values",True) # u'${rpar.values, plain=True}' on line 31, col 1
            if _v is not None: write(_filter(_v, plain=True, rawExpr=u'${rpar.values, plain=True}')) # from line 31, col 1.
            write(u'''
''')
        elif VFFSL(SL,"r.type",True) == 'single': # generated from line 32, col 1
            _v = VFN(VFFSL(SL,"rpar",True),"values",True)[0] # u'$rpar.values[0]' on line 33, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$rpar.values[0]')) # from line 33, col 1.
            write(u''' # One single value
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def output(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        self.main(trans=trans)
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_config= u'output'

## END CLASS DEFINITION

if not hasattr(config, '_initCheetahAttributes'):
    templateAPIClass = getattr(config, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(config)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=config()).run()


