#!/usr/bin/env python
import os,sys
import glob

print '# Generated by ' + sys.argv[0]
print 'quadratic(x,A,B,C) = A*(x**2) + B*x +C'
print 'dquadratic(x,A,B,C) = 2*A*x + B'

functions = {'piecewise':'quadratic','dpiecewise':'dquadratic'}

function_list = []

flist = glob.glob('elem_*.hard')

for id,datafile in sorted([ (int(os.path.splitext(f)[0].split('_')[1]),f) for f in flist]):
        # print datafile
        fields = open(datafile,'r').readlines()
        dd = {}
        dd['A'],dd['B'],dd['C'],dd['x0'],dd['x1'] = [float(f) for f in fields[1:6]]
        #A,B,C = 
        #x0,x1 = [float(i) for i in fields[4:6]]
        # print dd['x0'], dd['x1']
        function_list.append('x >= {x0} && x < {x1} ? {{fx}}(x,{A:e},{B:e},{C:e}) : \\'.format(**dd))
        last_term = '{{fx}}(x,{A:e},{B:e},{C:e}) )'.format(**dd)
  
for fxname,impfxname in functions.items():
        print (fxname + '(x) = ( \\')
        for line in function_list:
                print line.format(fx=impfxname)
        print last_term.format(fx=impfxname)
        


