#
# $Id$
#

# 
# Configuration on VIC3
# 
ifeq ($(BUILDHOST),vic3)
     # MKLROOT is set via environment variable
     MKLPATH=$(MKLROOT)/lib/$(MKL_TARGET_ARCH)
     MKLINCLUDE= -I$(MKLROOT)/include/$(MKL_TARGET_ARCH)/lp64
     MKLLDFLAGS += $(MKLPATH)/libmkl_solver_lp64_sequential.a -Wl,--start-group $(MKLPATH)/libmkl_intel_lp64.a $(MKLPATH)/libmkl_sequential.a $(MKLPATH)/libmkl_core.a -Wl,--end-group -lpthread
endif

#
# Configuration on dijkstra
# 
ifeq ($(BUILDHOST),dijkstra)
     # MKLROOT is set via environment variable
     MKLINCLUDE= -I$(MKLROOT)/include/$(MKL_TARGET_ARCH)/lp64
     MKLPATH=$(MKLROOT)/lib/$(MKL_TARGET_ARCH)
     MKLLDFLAGS += $(MKLPATH)/libmkl_solver_lp64_sequential.a -Wl,--start-group $(MKLPATH)/libmkl_intel_lp64.a $(MKLPATH)/libmkl_sequential.a $(MKLPATH)/libmkl_core.a -Wl,--end-group -lpthread
endif
#
