@echo off  
@rem Generated by $Id$ 
@rem Path to support tools 
set TEXSUPPORT_INSTALL=c:\work\TWRMTMProject\TWR\support-tex\twr-contrib
@rem Path to the directory containing common datasets 
set TEXSUPPORT_DATA=%TEXSUPPORT_INSTALL%\data
set PATH=c:\work\TWRMTMProject\TWR\support-tex\twr-contrib\compat\bin;%PATH%
